# SonarCloud configuration

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          organization: 'myorganization'  # Replace with your SonarCloud organization key
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          projectName: 'My Project'  # Replace with your project name
          sources: './'  # Specify the source code directory
          extraProperties: |
            sonar.qualitygate.wait=true  # Wait for the quality gate to pass

      - name: Check Quality Gate Status
        id: check_quality_gate
        run: |
          echo "::set-output name=passed::$(if [[ \$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}&branch=${{ github.ref }}" | jq -r '.projectStatus.status') == 'OK' ]]; then echo true; else echo false; fi)"

      - name: Push Code to Main
        if: ${{ needs.sonar_analysis.outputs.branch != 'main' && needs.check_quality_gate.outputs.passed == 'true' }}
        # Code push step configuration
        # ...